In [2]:
""""import numpy as np
k=2
Xst = np.array([[5,6,4,8,1],[3,8,6,2,5]])
temp =Xst
for i in range(k-1):
    
    c = np.vstack((temp, Xst))
    temp =c
a = [[1,0,-1,0,0,0],
    [1,0,0,-1,0,0],
    [0,1,0,0,-1,0],
    [0,1,0,0,0,-1]
    ]
new= np.hstack((a,c))

xxx= np.ones((1,11),dtype=int)
for i in range(6):
    xxx[0][i]=0
new= np.vstack((new,xxx))
print(new)

co= np.zeros((11,),dtype=int)
for i in range(6):
    co[i]=1"""

[[ 1  0 -1  0  0  0  5  6  4  8  1]
 [ 1  0  0 -1  0  0  3  8  6  2  5]
 [ 0  1  0  0 -1  0  5  6  4  8  1]
 [ 0  1  0  0  0 -1  3  8  6  2  5]
 [ 0  0  0  0  0  0  1  1  1  1  1]]


## section 1.4

In [22]:
from numpy import arange,array,ones,linalg, zeros
import numpy as np
from pylab import plot,show

from gurobipy import *

w=[1,1]
n=2

m = Model("projtest") 

x = []
#pour les zij

Ni= np.arange(n)
Nx = np.arange(5)
z1=[[5,6,4,8,1],[3,8,6,2,5]]
z2=[3,8,6,2,5]


b= m.addVars(Ni ,Ni,name="B",vtype=GRB.CONTINUOUS, lb=0)
r =m.addVars(Ni,name= "R",vtype=GRB.CONTINUOUS)
x =m.addVars(Nx,name= "X",vtype=GRB.BINARY)

m.update()
obj = LinExpr();
obj =0



obj = quicksum( w[k] * (( (k+1) * r[k]) - (quicksum(b[t,k] for t in Ni))) for k in Ni)

# definition de l'objectif
m.setObjective(obj,GRB.MAXIMIZE)

m.addConstr(quicksum(x[t] for t in Nx)==3)
for i in Ni:
    for k in Ni:

        m.addConstr(r[k] -b [i,k] <= quicksum(x[t]*z1[i][t] for t in Nx))


m.optimize()

#m.write("test.lp") 
print("")                
"""print('Solution optimale:')
for j in colonnes:
    print('x%d'%(j+1), '=', x[j].x)
print("")"""
print(m.getAttr(GRB.Attr.X, m.getVars()))
print('Valeur de la fonction objectif :', m.objVal) 


Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 5 rows, 11 columns and 33 nonzeros
Model fingerprint: 0xe36aaadd
Variable types: 6 continuous, 5 integer (5 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+00]
  Objective range  [1e+00, 2e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]
Found heuristic solution: objective 45.0000000
Presolve time: 0.00s
Presolved: 5 rows, 11 columns, 29 nonzeros
Variable types: 6 continuous, 5 integer (5 binary)

Root relaxation: objective 5.000000e+01, 7 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0      50.0000000   50.00000  0.00%     -    0s

Explored 0 nodes (7 simplex iterations) in 0.02 seconds
Thread count was 4 (of 4 available processors)

Solution

In [6]:
"""from numpy import arange,array,ones,linalg, zeros
import numpy as np
from pylab import plot,show

from gurobipy import *

k=2
n=2
# nbcont = k*2 + 1
nbcont= 5
nbvar=6+ 5
lignes = range(nbcont)
colonnes= range(nbvar)


m = Model("projex1") 

x = []
#r1 and r2
for i in range(2):
    x.append(m.addVar(vtype=GRB.CONTINUOUS, name="x%d" % (i+1)))
#b11 b21 b12 b22
for i in range(2,6):
    x.append(m.addVar(vtype=GRB.CONTINUOUS, lb=0, name="x%d" % (i+1)))
#x1... x5
for i in range(6,11):
    x.append(m.addVar(vtype=GRB.INTEGER, lb=0, ub=1, name="x%d" % (i+1)))
# maj du modele pour integrer les nouvelles variables
m.update()

obj = LinExpr();
obj =0
obj =  (x[0] -(x[2]+x[3])) + ((2*x[1])-(x[4]+x[5]))

# definition de l'objectif
m.setObjective(obj,GRB.MAXIMIZE)

for i in range(4):
    m.addConstr(quicksum(new[i][j]*x[j] for j in range(6)) <= quicksum(new[i][j]* x[j] for j in range(6,11)), "Contrainte%d" % i)

m.addConstr(quicksum (new[4][j]*x[j] for j in range(6,11)) == 3 , "Contrainte%d" % 4)

# Resolution
m.optimize()

print("")                
print('Solution optimale:')
for j in colonnes:
    print('x%d'%(j+1), '=', x[j].x)
print("")
print('Valeur de la fonction objectif :', m.objVal)
"""


Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 5 rows, 11 columns and 33 nonzeros
Model fingerprint: 0x5c843f7d
Variable types: 6 continuous, 5 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+00]
  Objective range  [1e+00, 2e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [3e+00, 3e+00]
Found heuristic solution: objective 45.0000000
Presolve time: 0.00s
Presolved: 5 rows, 11 columns, 29 nonzeros
Variable types: 6 continuous, 5 integer (5 binary)

Root relaxation: objective 5.000000e+01, 7 iterations, 0.00 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

*    0     0               0      50.0000000   50.00000  0.00%     -    0s

Explored 0 nodes (7 simplex iterations) in 0.02 seconds
Thread count was 4 (of 4 available processors)

Solution

## section 2.1

In [29]:
def get_wk(w:list)->list:
    wk = w.copy()
    for i in range(len(wk)-1):
        wk[i] = w[i] -w[i+1]
    return wk

w=[3,2,1]
print(get_wk(w))



[1, 1, 1]


In [31]:
n=3
p=6
u= np.random.randint(10, size=(n,p))
print(u)

[[3 6 9 5 9 2]
 [2 9 4 5 2 3]
 [4 0 2 5 1 7]]


In [53]:
from numpy import arange,array,ones,linalg, zeros
import numpy as np
from pylab import plot,show

from gurobipy import *

n=3
p=6

nbcont= n**2 +2*(p+n)
nbvarB=n*p
nbvarC= n**2 +n
lignes = range(nbcont)
colonnesB= range(nbvarB)
colonnesC= range(nbvarC)
w=get_wk([3,2,1])


m = Model("projex2") 

x = []
#pour les zij
Ni= np.arange(n)
Nj= np.arange(p)


z= m.addVars(Ni ,Nj,name="Z",vtype=GRB.BINARY)
b= m.addVars(Ni ,Ni,name="B",vtype=GRB.CONTINUOUS, lb=0)
r =m.addVars(Ni,name= "R",vtype=GRB.CONTINUOUS)

m.update()
obj = LinExpr();

obj = quicksum( w[k] * (( (k+1) * r[k]) - (quicksum(b[t,k] for t in Ni))) for k in Ni)

# definition de l'objectif
m.setObjective(obj,GRB.MAXIMIZE)

for j in Nj:
    m.addConstr(quicksum(z[i,j]for i in Ni)==1)
for i in Ni:
    m.addConstr(quicksum(z[i,j] for j in Nj)<=n)#### Beta 
    m.addConstr(quicksum(z[i,j] for j in Nj)>=0)##### apha

for i in Ni:
    for k in Ni:

        m.addConstr(r[k] -b [i,k] >= quicksum(z[i,p]*u[i,p] for p in Nj))
# Resolution
m.optimize()

m.write("exampl.lp")
print(f"matrix used{u}")
for v in z.values():
    print("{}: {}".format(v.varName, v.X))
vals = { k : v.X for k,v in z.items() }
d={}
for i in range(u.shape[0]):
    d[i] = quicksum(u[i,j]*vals[i,j] for j in range(u.shape[1]))
print(d)
print(vals)
print(z)

Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 21 rows, 30 columns and 123 nonzeros
Model fingerprint: 0x461cb5de
Variable types: 12 continuous, 18 integer (18 binary)
Coefficient statistics:
  Matrix range     [1e+00, 9e+00]
  Objective range  [1e+00, 3e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 3e+00]
Found heuristic solution: objective 6.000000e+30
Presolve removed 0 rows and 9 columns
Presolve time: 0.00s

Explored 0 nodes (0 simplex iterations) in 0.01 seconds
Thread count was 1 (of 4 available processors)

Solution count 1: 6e+30 
No other solutions better than 0

Model is unbounded
Best objective 6.000000000000e+30, best bound -, gap -
matrix used[[3 6 9 5 9 2]
 [2 9 4 5 2 3]
 [4 0 2 5 1 7]]
Z[0,0]: 0.0
Z[0,1]: 1.0
Z[0,2]: 0.0
Z[0,3]: 0.0
Z[0,4]: 1.0
Z[0,5]: 0.0
Z[1,0]: 0.0
Z[1,1]: 0.0
Z[1,2]: 0.0
Z[1,3]: 0.0
Z[1,4]: 0.0
Z[1,5]: 1.0
Z[2,0]: 1.0
Z[2,1]: